name: Windows-MSVC-CUDA (compile-only)

jobs:
  windows_cuda:
    strategy:
      fail-fast: false
      matrix:
        config:
        - {version: "10.2.89.20191206", name: "cuda102"}
        - {version: "latest", name: "cuda-latest"}
    name: msvc/${{ matrix.config.name }} (only compile)
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: setup (versioned)
      if: matrix.config.version != 'latest'
      run: |
        choco install cuda --version=${{ matrix.config.version }} -y

    - name: setup (latest)
      if: matrix.config.version == 'latest'
      run: |
        choco install cuda -y

    - name: configure
      run: |
        $env:ChocolateyInstall = Convert-Path "$((Get-Command choco).Path)\..\.."
        Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
        refreshenv
        nvcc hello.cu
